version: 0.2

run-as: root
phases:
  pre_build:
    commands:
      - echo "Assuming cross-account CodeBuild role..."
      - $(assume-role $PROFILE)
  build:
    commands:
      - echo "Deploying to $PROFILE..."
